// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/itsLeonB/cashback/internal/domain/dto"
	"github.com/itsLeonB/cashback/internal/domain/entity/users"
	"github.com/itsLeonB/cashback/internal/domain/message"
	"github.com/itsLeonB/cashback/internal/domain/service/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateNew provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateNew(ctx context.Context, request dto.NewUserRequest) (users.User, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateNew")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NewUserRequest) (users.User, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NewUserRequest) users.User); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.NewUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNew'
type MockUserService_CreateNew_Call struct {
	*mock.Call
}

// CreateNew is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.NewUserRequest
func (_e *MockUserService_Expecter) CreateNew(ctx interface{}, request interface{}) *MockUserService_CreateNew_Call {
	return &MockUserService_CreateNew_Call{Call: _e.mock.On("CreateNew", ctx, request)}
}

func (_c *MockUserService_CreateNew_Call) Run(run func(ctx context.Context, request dto.NewUserRequest)) *MockUserService_CreateNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.NewUserRequest
		if args[1] != nil {
			arg1 = args[1].(dto.NewUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateNew_Call) Return(user users.User, err error) *MockUserService_CreateNew_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_CreateNew_Call) RunAndReturn(run func(ctx context.Context, request dto.NewUserRequest) (users.User, error)) *MockUserService_CreateNew_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) FindByEmail(ctx context.Context, email string) (users.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (users.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) users.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserService_FindByEmail_Call {
	return &MockUserService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserService_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_FindByEmail_Call) Return(user users.User, err error) *MockUserService_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (users.User, error)) *MockUserService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePasswordResetToken provides a mock function for the type MockUserService
func (_mock *MockUserService) GeneratePasswordResetToken(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePasswordResetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GeneratePasswordResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePasswordResetToken'
type MockUserService_GeneratePasswordResetToken_Call struct {
	*mock.Call
}

// GeneratePasswordResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserService_Expecter) GeneratePasswordResetToken(ctx interface{}, userID interface{}) *MockUserService_GeneratePasswordResetToken_Call {
	return &MockUserService_GeneratePasswordResetToken_Call{Call: _e.mock.On("GeneratePasswordResetToken", ctx, userID)}
}

func (_c *MockUserService_GeneratePasswordResetToken_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserService_GeneratePasswordResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GeneratePasswordResetToken_Call) Return(s string, err error) *MockUserService_GeneratePasswordResetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_GeneratePasswordResetToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockUserService_GeneratePasswordResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByID(ctx context.Context, id uuid.UUID) (users.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (users.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) users.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserService_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserService_GetByID_Call {
	return &MockUserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByID_Call) Return(user users.User, err error) *MockUserService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (users.User, error)) *MockUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockUserService
func (_mock *MockUserService) ResetPassword(ctx context.Context, userID uuid.UUID, email string, resetToken string, password string) (users.User, error) {
	ret := _mock.Called(ctx, userID, email, resetToken, password)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (users.User, error)); ok {
		return returnFunc(ctx, userID, email, resetToken, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) users.User); ok {
		r0 = returnFunc(ctx, userID, email, resetToken, password)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = returnFunc(ctx, userID, email, resetToken, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockUserService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - email string
//   - resetToken string
//   - password string
func (_e *MockUserService_Expecter) ResetPassword(ctx interface{}, userID interface{}, email interface{}, resetToken interface{}, password interface{}) *MockUserService_ResetPassword_Call {
	return &MockUserService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, userID, email, resetToken, password)}
}

func (_c *MockUserService_ResetPassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, email string, resetToken string, password string)) *MockUserService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserService_ResetPassword_Call) Return(user users.User, err error) *MockUserService_ResetPassword_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, email string, resetToken string, password string) (users.User, error)) *MockUserService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SendSubscriptionNearingDueDateMail provides a mock function for the type MockUserService
func (_mock *MockUserService) SendSubscriptionNearingDueDateMail(ctx context.Context, msg message.SubscriptionNearingDue) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendSubscriptionNearingDueDateMail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, message.SubscriptionNearingDue) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_SendSubscriptionNearingDueDateMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSubscriptionNearingDueDateMail'
type MockUserService_SendSubscriptionNearingDueDateMail_Call struct {
	*mock.Call
}

// SendSubscriptionNearingDueDateMail is a helper method to define mock.On call
//   - ctx context.Context
//   - msg message.SubscriptionNearingDue
func (_e *MockUserService_Expecter) SendSubscriptionNearingDueDateMail(ctx interface{}, msg interface{}) *MockUserService_SendSubscriptionNearingDueDateMail_Call {
	return &MockUserService_SendSubscriptionNearingDueDateMail_Call{Call: _e.mock.On("SendSubscriptionNearingDueDateMail", ctx, msg)}
}

func (_c *MockUserService_SendSubscriptionNearingDueDateMail_Call) Run(run func(ctx context.Context, msg message.SubscriptionNearingDue)) *MockUserService_SendSubscriptionNearingDueDateMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 message.SubscriptionNearingDue
		if args[1] != nil {
			arg1 = args[1].(message.SubscriptionNearingDue)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_SendSubscriptionNearingDueDateMail_Call) Return(err error) *MockUserService_SendSubscriptionNearingDueDateMail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_SendSubscriptionNearingDueDateMail_Call) RunAndReturn(run func(ctx context.Context, msg message.SubscriptionNearingDue) error) *MockUserService_SendSubscriptionNearingDueDateMail_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockUserService
func (_mock *MockUserService) Verify(ctx context.Context, id uuid.UUID, email string, name string, avatar string) (users.User, error) {
	ret := _mock.Called(ctx, id, email, name, avatar)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 users.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (users.User, error)); ok {
		return returnFunc(ctx, id, email, name, avatar)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) users.User); ok {
		r0 = returnFunc(ctx, id, email, name, avatar)
	} else {
		r0 = ret.Get(0).(users.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, email, name, avatar)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockUserService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - email string
//   - name string
//   - avatar string
func (_e *MockUserService_Expecter) Verify(ctx interface{}, id interface{}, email interface{}, name interface{}, avatar interface{}) *MockUserService_Verify_Call {
	return &MockUserService_Verify_Call{Call: _e.mock.On("Verify", ctx, id, email, name, avatar)}
}

func (_c *MockUserService_Verify_Call) Run(run func(ctx context.Context, id uuid.UUID, email string, name string, avatar string)) *MockUserService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserService_Verify_Call) Return(user users.User, err error) *MockUserService_Verify_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Verify_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, email string, name string, avatar string) (users.User, error)) *MockUserService_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// InternalLogin provides a mock function for the type MockAuthService
func (_mock *MockAuthService) InternalLogin(ctx context.Context, request dto.InternalLoginRequest) (dto.TokenResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for InternalLogin")
	}

	var r0 dto.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.InternalLoginRequest) (dto.TokenResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.InternalLoginRequest) dto.TokenResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.InternalLoginRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_InternalLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InternalLogin'
type MockAuthService_InternalLogin_Call struct {
	*mock.Call
}

// InternalLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.InternalLoginRequest
func (_e *MockAuthService_Expecter) InternalLogin(ctx interface{}, request interface{}) *MockAuthService_InternalLogin_Call {
	return &MockAuthService_InternalLogin_Call{Call: _e.mock.On("InternalLogin", ctx, request)}
}

func (_c *MockAuthService_InternalLogin_Call) Run(run func(ctx context.Context, request dto.InternalLoginRequest)) *MockAuthService_InternalLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.InternalLoginRequest
		if args[1] != nil {
			arg1 = args[1].(dto.InternalLoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_InternalLogin_Call) Return(tokenResponse dto.TokenResponse, err error) *MockAuthService_InternalLogin_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockAuthService_InternalLogin_Call) RunAndReturn(run func(ctx context.Context, request dto.InternalLoginRequest) (dto.TokenResponse, error)) *MockAuthService_InternalLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Logout(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, sessionID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(err error) *MockAuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, request dto.RegisterRequest) (dto.RegisterResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 dto.RegisterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest) (dto.RegisterResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest) dto.RegisterResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.RegisterResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.RegisterRequest
func (_e *MockAuthService_Expecter) Register(ctx interface{}, request interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, request dto.RegisterRequest)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(dto.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(registerResponse dto.RegisterResponse, err error) *MockAuthService_Register_Call {
	_c.Call.Return(registerResponse, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, request dto.RegisterRequest) (dto.RegisterResponse, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ResetPassword(ctx context.Context, token string, newPassword string) (dto.TokenResponse, error) {
	ret := _mock.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 dto.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (dto.TokenResponse, error)); ok {
		return returnFunc(ctx, token, newPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) dto.TokenResponse); ok {
		r0 = returnFunc(ctx, token, newPassword)
	} else {
		r0 = ret.Get(0).(dto.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, newPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockAuthService_Expecter) ResetPassword(ctx interface{}, token interface{}, newPassword interface{}) *MockAuthService_ResetPassword_Call {
	return &MockAuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *MockAuthService_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockAuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) Return(tokenResponse dto.TokenResponse, err error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, token string, newPassword string) (dto.TokenResponse, error)) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SendPasswordReset provides a mock function for the type MockAuthService
func (_mock *MockAuthService) SendPasswordReset(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_SendPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordReset'
type MockAuthService_SendPasswordReset_Call struct {
	*mock.Call
}

// SendPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthService_Expecter) SendPasswordReset(ctx interface{}, email interface{}) *MockAuthService_SendPasswordReset_Call {
	return &MockAuthService_SendPasswordReset_Call{Call: _e.mock.On("SendPasswordReset", ctx, email)}
}

func (_c *MockAuthService_SendPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockAuthService_SendPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_SendPasswordReset_Call) Return(err error) *MockAuthService_SendPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_SendPasswordReset_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthService_SendPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockAuthService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockAuthService_Expecter) Shutdown() *MockAuthService_Shutdown_Call {
	return &MockAuthService_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockAuthService_Shutdown_Call) Run(run func()) *MockAuthService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthService_Shutdown_Call) Return(err error) *MockAuthService_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Shutdown_Call) RunAndReturn(run func() error) *MockAuthService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRegistration provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyRegistration(ctx context.Context, token string) (dto.TokenResponse, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRegistration")
	}

	var r0 dto.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dto.TokenResponse, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dto.TokenResponse); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(dto.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_VerifyRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRegistration'
type MockAuthService_VerifyRegistration_Call struct {
	*mock.Call
}

// VerifyRegistration is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) VerifyRegistration(ctx interface{}, token interface{}) *MockAuthService_VerifyRegistration_Call {
	return &MockAuthService_VerifyRegistration_Call{Call: _e.mock.On("VerifyRegistration", ctx, token)}
}

func (_c *MockAuthService_VerifyRegistration_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_VerifyRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyRegistration_Call) Return(tokenResponse dto.TokenResponse, err error) *MockAuthService_VerifyRegistration_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockAuthService_VerifyRegistration_Call) RunAndReturn(run func(ctx context.Context, token string) (dto.TokenResponse, error)) *MockAuthService_VerifyRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyToken(ctx context.Context, token string, fingerprint string) (bool, map[string]any, error) {
	ret := _mock.Called(ctx, token, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 bool
	var r1 map[string]any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, map[string]any, error)); ok {
		return returnFunc(ctx, token, fingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, token, fingerprint)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) map[string]any); ok {
		r1 = returnFunc(ctx, token, fingerprint)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, token, fingerprint)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockAuthService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - fingerprint string
func (_e *MockAuthService_Expecter) VerifyToken(ctx interface{}, token interface{}, fingerprint interface{}) *MockAuthService_VerifyToken_Call {
	return &MockAuthService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token, fingerprint)}
}

func (_c *MockAuthService_VerifyToken_Call) Run(run func(ctx context.Context, token string, fingerprint string)) *MockAuthService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyToken_Call) Return(b bool, stringToV map[string]any, err error) *MockAuthService_VerifyToken_Call {
	_c.Call.Return(b, stringToV, err)
	return _c
}

func (_c *MockAuthService_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string, fingerprint string) (bool, map[string]any, error)) *MockAuthService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

type MockSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionService) EXPECT() *MockSessionService_Expecter {
	return &MockSessionService_Expecter{mock: &_m.Mock}
}

// CreateTokenAndSession provides a mock function for the type MockSessionService
func (_mock *MockSessionService) CreateTokenAndSession(ctx context.Context, user auth.User) (dto.TokenResponse, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokenAndSession")
	}

	var r0 dto.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.User) (dto.TokenResponse, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.User) dto.TokenResponse); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(dto.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_CreateTokenAndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokenAndSession'
type MockSessionService_CreateTokenAndSession_Call struct {
	*mock.Call
}

// CreateTokenAndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user auth.User
func (_e *MockSessionService_Expecter) CreateTokenAndSession(ctx interface{}, user interface{}) *MockSessionService_CreateTokenAndSession_Call {
	return &MockSessionService_CreateTokenAndSession_Call{Call: _e.mock.On("CreateTokenAndSession", ctx, user)}
}

func (_c *MockSessionService_CreateTokenAndSession_Call) Run(run func(ctx context.Context, user auth.User)) *MockSessionService_CreateTokenAndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.User
		if args[1] != nil {
			arg1 = args[1].(auth.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_CreateTokenAndSession_Call) Return(tokenResponse dto.TokenResponse, err error) *MockSessionService_CreateTokenAndSession_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockSessionService_CreateTokenAndSession_Call) RunAndReturn(run func(ctx context.Context, user auth.User) (dto.TokenResponse, error)) *MockSessionService_CreateTokenAndSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockSessionService
func (_mock *MockSessionService) GetByID(ctx context.Context, id string) (auth.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 auth.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(auth.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSessionService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionService_Expecter) GetByID(ctx interface{}, id interface{}) *MockSessionService_GetByID_Call {
	return &MockSessionService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSessionService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockSessionService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_GetByID_Call) Return(session auth.Session, err error) *MockSessionService_GetByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (auth.Session, error)) *MockSessionService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockSessionService
func (_mock *MockSessionService) RefreshToken(ctx context.Context, request dto.RefreshTokenRequest) (dto.TokenResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 dto.TokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.RefreshTokenRequest) (dto.TokenResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.RefreshTokenRequest) dto.TokenResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.RefreshTokenRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockSessionService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.RefreshTokenRequest
func (_e *MockSessionService_Expecter) RefreshToken(ctx interface{}, request interface{}) *MockSessionService_RefreshToken_Call {
	return &MockSessionService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, request)}
}

func (_c *MockSessionService_RefreshToken_Call) Run(run func(ctx context.Context, request dto.RefreshTokenRequest)) *MockSessionService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.RefreshTokenRequest
		if args[1] != nil {
			arg1 = args[1].(dto.RefreshTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_RefreshToken_Call) Return(tokenResponse dto.TokenResponse, err error) *MockSessionService_RefreshToken_Call {
	_c.Call.Return(tokenResponse, err)
	return _c
}

func (_c *MockSessionService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, request dto.RefreshTokenRequest) (dto.TokenResponse, error)) *MockSessionService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockSessionService
func (_mock *MockSessionService) RevokeSession(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionService_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionService_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionService_Expecter) RevokeSession(ctx interface{}, sessionID interface{}) *MockSessionService_RevokeSession_Call {
	return &MockSessionService_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID)}
}

func (_c *MockSessionService_RevokeSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionService_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_RevokeSession_Call) Return(err error) *MockSessionService_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionService_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionService_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileService creates a new instance of MockProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileService {
	mock := &MockProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileService is an autogenerated mock type for the ProfileService type
type MockProfileService struct {
	mock.Mock
}

type MockProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileService) EXPECT() *MockProfileService_Expecter {
	return &MockProfileService_Expecter{mock: &_m.Mock}
}

// Associate provides a mock function for the type MockProfileService
func (_mock *MockProfileService) Associate(ctx context.Context, userProfileID uuid.UUID, realProfileID uuid.UUID, anonProfileID uuid.UUID) error {
	ret := _mock.Called(ctx, userProfileID, realProfileID, anonProfileID)

	if len(ret) == 0 {
		panic("no return value specified for Associate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userProfileID, realProfileID, anonProfileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileService_Associate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Associate'
type MockProfileService_Associate_Call struct {
	*mock.Call
}

// Associate is a helper method to define mock.On call
//   - ctx context.Context
//   - userProfileID uuid.UUID
//   - realProfileID uuid.UUID
//   - anonProfileID uuid.UUID
func (_e *MockProfileService_Expecter) Associate(ctx interface{}, userProfileID interface{}, realProfileID interface{}, anonProfileID interface{}) *MockProfileService_Associate_Call {
	return &MockProfileService_Associate_Call{Call: _e.mock.On("Associate", ctx, userProfileID, realProfileID, anonProfileID)}
}

func (_c *MockProfileService_Associate_Call) Run(run func(ctx context.Context, userProfileID uuid.UUID, realProfileID uuid.UUID, anonProfileID uuid.UUID)) *MockProfileService_Associate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProfileService_Associate_Call) Return(err error) *MockProfileService_Associate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileService_Associate_Call) RunAndReturn(run func(ctx context.Context, userProfileID uuid.UUID, realProfileID uuid.UUID, anonProfileID uuid.UUID) error) *MockProfileService_Associate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockProfileService
func (_mock *MockProfileService) Create(ctx context.Context, request dto.NewProfileRequest) (dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NewProfileRequest) (dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NewProfileRequest) dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.ProfileResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.NewProfileRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProfileService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.NewProfileRequest
func (_e *MockProfileService_Expecter) Create(ctx interface{}, request interface{}) *MockProfileService_Create_Call {
	return &MockProfileService_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockProfileService_Create_Call) Run(run func(ctx context.Context, request dto.NewProfileRequest)) *MockProfileService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.NewProfileRequest
		if args[1] != nil {
			arg1 = args[1].(dto.NewProfileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_Create_Call) Return(profileResponse dto.ProfileResponse, err error) *MockProfileService_Create_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileService_Create_Call) RunAndReturn(run func(ctx context.Context, request dto.NewProfileRequest) (dto.ProfileResponse, error)) *MockProfileService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function for the type MockProfileService
func (_mock *MockProfileService) FindBySlug(ctx context.Context, slug string) (users.UserProfile, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (users.UserProfile, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) users.UserProfile); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(users.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockProfileService_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockProfileService_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockProfileService_FindBySlug_Call {
	return &MockProfileService_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockProfileService_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockProfileService_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_FindBySlug_Call) Return(userProfile users.UserProfile, err error) *MockProfileService_FindBySlug_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockProfileService_FindBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (users.UserProfile, error)) *MockProfileService_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetAll(ctx context.Context) ([]dto.ProfileResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.ProfileResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.ProfileResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProfileService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileService_Expecter) GetAll(ctx interface{}) *MockProfileService_GetAll_Call {
	return &MockProfileService_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockProfileService_GetAll_Call) Run(run func(ctx context.Context)) *MockProfileService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileService_GetAll_Call) Return(profileResponses []dto.ProfileResponse, err error) *MockProfileService_GetAll_Call {
	_c.Call.Return(profileResponses, err)
	return _c
}

func (_c *MockProfileService_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]dto.ProfileResponse, error)) *MockProfileService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllReal provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetAllReal(ctx context.Context) ([]dto.ProfileResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllReal")
	}

	var r0 []dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.ProfileResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.ProfileResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetAllReal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllReal'
type MockProfileService_GetAllReal_Call struct {
	*mock.Call
}

// GetAllReal is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfileService_Expecter) GetAllReal(ctx interface{}) *MockProfileService_GetAllReal_Call {
	return &MockProfileService_GetAllReal_Call{Call: _e.mock.On("GetAllReal", ctx)}
}

func (_c *MockProfileService_GetAllReal_Call) Run(run func(ctx context.Context)) *MockProfileService_GetAllReal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfileService_GetAllReal_Call) Return(profileResponses []dto.ProfileResponse, err error) *MockProfileService_GetAllReal_Call {
	_c.Call.Return(profileResponses, err)
	return _c
}

func (_c *MockProfileService_GetAllReal_Call) RunAndReturn(run func(ctx context.Context) ([]dto.ProfileResponse, error)) *MockProfileService_GetAllReal_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssociatedIDs provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetAssociatedIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAssociatedIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetAssociatedIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssociatedIDs'
type MockProfileService_GetAssociatedIDs_Call struct {
	*mock.Call
}

// GetAssociatedIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProfileService_Expecter) GetAssociatedIDs(ctx interface{}, id interface{}) *MockProfileService_GetAssociatedIDs_Call {
	return &MockProfileService_GetAssociatedIDs_Call{Call: _e.mock.On("GetAssociatedIDs", ctx, id)}
}

func (_c *MockProfileService_GetAssociatedIDs_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProfileService_GetAssociatedIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetAssociatedIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockProfileService_GetAssociatedIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockProfileService_GetAssociatedIDs_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)) *MockProfileService_GetAssociatedIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetByID(ctx context.Context, id uuid.UUID) (dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.ProfileResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProfileService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProfileService_Expecter) GetByID(ctx interface{}, id interface{}) *MockProfileService_GetByID_Call {
	return &MockProfileService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProfileService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProfileService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetByID_Call) Return(profileResponse dto.ProfileResponse, err error) *MockProfileService_GetByID_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (dto.ProfileResponse, error)) *MockProfileService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetByIDs(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 map[uuid.UUID]dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]dto.ProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockProfileService_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockProfileService_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockProfileService_GetByIDs_Call {
	return &MockProfileService_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockProfileService_GetByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockProfileService_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetByIDs_Call) Return(uUIDToProfileResponse map[uuid.UUID]dto.ProfileResponse, err error) *MockProfileService_GetByIDs_Call {
	_c.Call.Return(uUIDToProfileResponse, err)
	return _c
}

func (_c *MockProfileService_GetByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]dto.ProfileResponse, error)) *MockProfileService_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityByID provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetEntityByID(ctx context.Context, id uuid.UUID) (users.UserProfile, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityByID")
	}

	var r0 users.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (users.UserProfile, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) users.UserProfile); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(users.UserProfile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetEntityByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityByID'
type MockProfileService_GetEntityByID_Call struct {
	*mock.Call
}

// GetEntityByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProfileService_Expecter) GetEntityByID(ctx interface{}, id interface{}) *MockProfileService_GetEntityByID_Call {
	return &MockProfileService_GetEntityByID_Call{Call: _e.mock.On("GetEntityByID", ctx, id)}
}

func (_c *MockProfileService_GetEntityByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProfileService_GetEntityByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetEntityByID_Call) Return(userProfile users.UserProfile, err error) *MockProfileService_GetEntityByID_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockProfileService_GetEntityByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (users.UserProfile, error)) *MockProfileService_GetEntityByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealProfileID provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetRealProfileID(ctx context.Context, anonProfileID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, anonProfileID)

	if len(ret) == 0 {
		panic("no return value specified for GetRealProfileID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, anonProfileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, anonProfileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, anonProfileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetRealProfileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealProfileID'
type MockProfileService_GetRealProfileID_Call struct {
	*mock.Call
}

// GetRealProfileID is a helper method to define mock.On call
//   - ctx context.Context
//   - anonProfileID uuid.UUID
func (_e *MockProfileService_Expecter) GetRealProfileID(ctx interface{}, anonProfileID interface{}) *MockProfileService_GetRealProfileID_Call {
	return &MockProfileService_GetRealProfileID_Call{Call: _e.mock.On("GetRealProfileID", ctx, anonProfileID)}
}

func (_c *MockProfileService_GetRealProfileID_Call) Run(run func(ctx context.Context, anonProfileID uuid.UUID)) *MockProfileService_GetRealProfileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetRealProfileID_Call) Return(uUID uuid.UUID, err error) *MockProfileService_GetRealProfileID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockProfileService_GetRealProfileID_Call) RunAndReturn(run func(ctx context.Context, anonProfileID uuid.UUID) (uuid.UUID, error)) *MockProfileService_GetRealProfileID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockProfileService
func (_mock *MockProfileService) Search(ctx context.Context, profileID uuid.UUID, input string) ([]dto.SearchProfileResponse, error) {
	ret := _mock.Called(ctx, profileID, input)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []dto.SearchProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]dto.SearchProfileResponse, error)); ok {
		return returnFunc(ctx, profileID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []dto.SearchProfileResponse); ok {
		r0 = returnFunc(ctx, profileID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SearchProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, profileID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProfileService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
//   - input string
func (_e *MockProfileService_Expecter) Search(ctx interface{}, profileID interface{}, input interface{}) *MockProfileService_Search_Call {
	return &MockProfileService_Search_Call{Call: _e.mock.On("Search", ctx, profileID, input)}
}

func (_c *MockProfileService_Search_Call) Run(run func(ctx context.Context, profileID uuid.UUID, input string)) *MockProfileService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileService_Search_Call) Return(searchProfileResponses []dto.SearchProfileResponse, err error) *MockProfileService_Search_Call {
	_c.Call.Return(searchProfileResponses, err)
	return _c
}

func (_c *MockProfileService_Search_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID, input string) ([]dto.SearchProfileResponse, error)) *MockProfileService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProfileService
func (_mock *MockProfileService) Update(ctx context.Context, req dto.UpdateProfileRequest) (dto.ProfileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.ProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateProfileRequest) (dto.ProfileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.UpdateProfileRequest) dto.ProfileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.ProfileResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.UpdateProfileRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProfileService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.UpdateProfileRequest
func (_e *MockProfileService_Expecter) Update(ctx interface{}, req interface{}) *MockProfileService_Update_Call {
	return &MockProfileService_Update_Call{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *MockProfileService_Update_Call) Run(run func(ctx context.Context, req dto.UpdateProfileRequest)) *MockProfileService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.UpdateProfileRequest
		if args[1] != nil {
			arg1 = args[1].(dto.UpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_Update_Call) Return(profileResponse dto.ProfileResponse, err error) *MockProfileService_Update_Call {
	_c.Call.Return(profileResponse, err)
	return _c
}

func (_c *MockProfileService_Update_Call) RunAndReturn(run func(ctx context.Context, req dto.UpdateProfileRequest) (dto.ProfileResponse, error)) *MockProfileService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionLimitService creates a new instance of MockSubscriptionLimitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionLimitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionLimitService {
	mock := &MockSubscriptionLimitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionLimitService is an autogenerated mock type for the SubscriptionLimitService type
type MockSubscriptionLimitService struct {
	mock.Mock
}

type MockSubscriptionLimitService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionLimitService) EXPECT() *MockSubscriptionLimitService_Expecter {
	return &MockSubscriptionLimitService_Expecter{mock: &_m.Mock}
}

// CheckUploadLimit provides a mock function for the type MockSubscriptionLimitService
func (_mock *MockSubscriptionLimitService) CheckUploadLimit(ctx context.Context, profileID uuid.UUID) error {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for CheckUploadLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionLimitService_CheckUploadLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUploadLimit'
type MockSubscriptionLimitService_CheckUploadLimit_Call struct {
	*mock.Call
}

// CheckUploadLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
func (_e *MockSubscriptionLimitService_Expecter) CheckUploadLimit(ctx interface{}, profileID interface{}) *MockSubscriptionLimitService_CheckUploadLimit_Call {
	return &MockSubscriptionLimitService_CheckUploadLimit_Call{Call: _e.mock.On("CheckUploadLimit", ctx, profileID)}
}

func (_c *MockSubscriptionLimitService_CheckUploadLimit_Call) Run(run func(ctx context.Context, profileID uuid.UUID)) *MockSubscriptionLimitService_CheckUploadLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionLimitService_CheckUploadLimit_Call) Return(err error) *MockSubscriptionLimitService_CheckUploadLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionLimitService_CheckUploadLimit_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID) error) *MockSubscriptionLimitService_CheckUploadLimit_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrent provides a mock function for the type MockSubscriptionLimitService
func (_mock *MockSubscriptionLimitService) GetCurrent(ctx context.Context, profileID uuid.UUID) (dto.SubscriptionResponse, error) {
	ret := _mock.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrent")
	}

	var r0 dto.SubscriptionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.SubscriptionResponse, error)); ok {
		return returnFunc(ctx, profileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.SubscriptionResponse); ok {
		r0 = returnFunc(ctx, profileID)
	} else {
		r0 = ret.Get(0).(dto.SubscriptionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionLimitService_GetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrent'
type MockSubscriptionLimitService_GetCurrent_Call struct {
	*mock.Call
}

// GetCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID uuid.UUID
func (_e *MockSubscriptionLimitService_Expecter) GetCurrent(ctx interface{}, profileID interface{}) *MockSubscriptionLimitService_GetCurrent_Call {
	return &MockSubscriptionLimitService_GetCurrent_Call{Call: _e.mock.On("GetCurrent", ctx, profileID)}
}

func (_c *MockSubscriptionLimitService_GetCurrent_Call) Run(run func(ctx context.Context, profileID uuid.UUID)) *MockSubscriptionLimitService_GetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionLimitService_GetCurrent_Call) Return(subscriptionResponse dto.SubscriptionResponse, err error) *MockSubscriptionLimitService_GetCurrent_Call {
	_c.Call.Return(subscriptionResponse, err)
	return _c
}

func (_c *MockSubscriptionLimitService_GetCurrent_Call) RunAndReturn(run func(ctx context.Context, profileID uuid.UUID) (dto.SubscriptionResponse, error)) *MockSubscriptionLimitService_GetCurrent_Call {
	_c.Call.Return(run)
	return _c
}
