// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/itsLeonB/sekure"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockJWTService
func (_mock *MockJWTService) CreateToken(data map[string]any) (string, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]any) (string, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]any) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]any) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockJWTService_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - data map[string]any
func (_e *MockJWTService_Expecter) CreateToken(data interface{}) *MockJWTService_CreateToken_Call {
	return &MockJWTService_CreateToken_Call{Call: _e.mock.On("CreateToken", data)}
}

func (_c *MockJWTService_CreateToken_Call) Run(run func(data map[string]any)) *MockJWTService_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]any
		if args[0] != nil {
			arg0 = args[0].(map[string]any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTService_CreateToken_Call) Return(s string, err error) *MockJWTService_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTService_CreateToken_Call) RunAndReturn(run func(data map[string]any) (string, error)) *MockJWTService_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockJWTService
func (_mock *MockJWTService) VerifyToken(tokenstr string) (sekure.JWTClaims, error) {
	ret := _mock.Called(tokenstr)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 sekure.JWTClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (sekure.JWTClaims, error)); ok {
		return returnFunc(tokenstr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) sekure.JWTClaims); ok {
		r0 = returnFunc(tokenstr)
	} else {
		r0 = ret.Get(0).(sekure.JWTClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenstr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockJWTService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - tokenstr string
func (_e *MockJWTService_Expecter) VerifyToken(tokenstr interface{}) *MockJWTService_VerifyToken_Call {
	return &MockJWTService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", tokenstr)}
}

func (_c *MockJWTService_VerifyToken_Call) Run(run func(tokenstr string)) *MockJWTService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTService_VerifyToken_Call) Return(jWTClaims sekure.JWTClaims, err error) *MockJWTService_VerifyToken_Call {
	_c.Call.Return(jWTClaims, err)
	return _c
}

func (_c *MockJWTService_VerifyToken_Call) RunAndReturn(run func(tokenstr string) (sekure.JWTClaims, error)) *MockJWTService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
